language: generic
sudo: required
services:
  - docker

env:
  - NODE_VERSION=8-alpine
  - NODE_VERSION=10-alpine

  # - NPM_TARGET=test
  # - NPM_TARGET=start

before_install:
  - docker pull node:10-alpine

install:
  - docker build -t docker-demo .

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="{NODE_VERSION}" .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/docker-demo:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push $DOCKER_USERNAME/docker-demo:$NODE_VERSION-$(git rev-parse HEAD)
# make sure to create repository on dockerhub hence wont work

stages:
  - test
  - npm-targets

jobs:
  include:
    - stage: npm-targets
      name: "Test 10-alpine"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/docker-demo:$NODE_VERSION-$(git rev-parse HEAD)
      env:
        - NODE_VERSION=10-alpine
        - NPM_TARGET=test
    - stage: npm-targets
      name: "Test 10-alpine"
      install: skip
      script:
        - docker run --rm $DOCKER_USERNAME/docker-demo:$NODE_VERSION-$(git rev-parse HEAD)
      env:
        - NODE_VERSION=10-alpine
        - NPM_TARGET=start
