language: generic
sudo: required
services:
  - docker

env:
  - NPM_TARGET=test
  # - NPM_TARGET=coverage

before_install:
  - docker pull node:10-alpine

install:
  - docker build -t docker-demo .

script:
  - docker run --rm docker-demo npm run $NPM_TARGET

after_success:
  - set -x -v;
    set -e;
    if [ "NPM_TARGET" = "test"]; then
    - docker tag docker-demo docker-demo:$(git rev-parse HEAD)
    else
    echo "skipping docker tag"
    fi;
    docker images;
    set +x +v;
